/etc/systemd/system/nextcloudprev.timer|0644|root|root
[Unit]
Description=Run Nextcloud preview generator every 60 minutes

[Timer]
OnBootSec=60min
OnUnitActiveSec=60min
Unit=nextcloudprev.service

[Install]
WantedBy=timers.target
