/etc/systemd/system/nextcloudcron.service|0644|root|root
[Unit]
Description=Nextcloud cron.php job

[Service]
User=wwwrun
ExecCondition=/usr/bin/php -f /srv/www/htdocs/nextcloud/occ status -e
ExecStart=/usr/bin/php -f /srv/www/htdocs/nextcloud/cron.php
KillMode=process
