/etc/systemd/system/nextcloudprev.service|0644|root|root
[Unit]
Description=Nextcloud preview generator job

[Service]
User=wwwrun
ExecCondition=/usr/bin/php -f /srv/www/htdocs/nextcloud/occ status -e
ExecStart=/usr/bin/php -f /srv/www/htdocs/nextcloud/occ preview:pre-generate
KillMode=process
