/etc/redis/cache.conf|0644|root|root
# --- Ecoute via socket Unix (locale) ---
port 0
unixsocket /var/run/redis/cache.sock
unixsocketperm 660
protected-mode yes

daemonize no
supervised systemd
pidfile /var/run/redis/cache.pid

loglevel notice
logfile /var/log/redis/cache.log

databases 1

# --- Pas de persistance pour un cache ---
save ""
appendonly no
appendfsync no
stop-writes-on-bgsave-error no
rdbcompression no
rdbchecksum no
dbfilename ""
dir /var/lib/redis

# --- Mémoire & Eviction (cache agressif) ---
maxmemory 2gb
maxmemory-policy allkeys-lru

# --- Clients lents ---
client-output-buffer-limit normal 128mb 32mb 60
client-output-buffer-limit pubsub 32mb 8mb 60

# --- Perf & maintenance ---
activerehashing yes
hz 10
dynamic-hz yes
jemalloc-bg-thread yes

# --- Observabilité ---
slowlog-log-slower-than 10000
slowlog-max-len 256
latency-monitor-threshold 100

set-proc-title yes
proc-title-template "{title} {listen-addr} {server-mode}"
notify-keyspace-events ""
