/etc/apache2/vhosts.d/nextcloud.conf|0644|root|root
<VirtualHost *:80>
    ServerName sduz.uk.to
    DocumentRoot /srv/www/htdocs/nextcloud
    Redirect permanent / https://sduz.uk.to/
</VirtualHost>

<Proxy "fcgi://localhost/">
    ProxySet timeout=3600
</Proxy>

<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerName sduz.uk.to
    DocumentRoot /srv/www/htdocs/nextcloud

    <Directory /srv/www/htdocs/nextcloud>
        Options -Indexes -MultiViews +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    <FilesMatch "\.php$">
        SetHandler "proxy:unix:/var/run/php-fpm/www.sock|fcgi://localhost/"
    </FilesMatch>

    Timeout 3600
    ProxyTimeout 3600
    RequestReadTimeout body=0,MinRate=1

    LimitRequestBody 0

    ErrorLog /var/log/apache2/nextcloud_ssl_error.log
    CustomLog /var/log/apache2/nextcloud_ssl_access.log combined

    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/sduz.uk.to/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/sduz.uk.to/privkey.pem

    SSLProtocol -all +TLSv1.2 +TLSv1.3
    SSLCipherSuite HIGH:!aNULL:!MD5
    SSLHonorCipherOrder On

    Protocols h2 http/1.1

    <IfModule mod_headers.c>
        Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
        Header always set Referrer-Policy "no-referrer"
        Header always set X-Content-Type-Options "nosniff"
        Header always set X-Frame-Options "SAMEORIGIN"
        Header always set X-XSS-Protection "1; mode=block"
        Header always set Permissions-Policy "interest-cohort=()"
    </IfModule>
</VirtualHost>
</IfModule>
